app:
  name: Fiscalizacion Util application
  api:
    title: Fiscalizacion Util APIs
    version: 1.0.0
    description: APIs libros
    base-package: com.libros
    contact-name: Joel Ramirez
    contact-email: joel-rvas@outlook.com
    swagger:
      enable: true
server:
  port: 5001
  servlet:
    context-path: /v1
logging:
  level:
    root: DEBUG
    com.canvia: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{REQUEST_ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
spring:
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      database: biblioteca
      uri: mongodb://192.168.3.70:27017

aplication:
  servers:
    - ip: '0.0.0.0'
      path: '/v1'

spring.jackson.default-property-inclusion: non_null